#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE TABLE users (
		user_id     integer PRIMARY KEY generated by default as identity,
		user_name   varchar(50) NOT NULL UNIQUE,
		first_name  varchar(255) NOT NULL,
		last_name   varchar(255) NOT NULL,
		email       varchar(255) NOT NULL,
		user_status varchar(1) NOT NULL,
		department  varchar(255) DEFAULT NULL
	);
EOSQL
